services:
  app:
    build: ./docker
    image: burashev/php_mvc
    ports:
      - "8080:80"
    volumes:
      # Mount source-code for development
      - ./:/var/www
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvc_framework
      MYSQL_USER: framework_user
      MYSQL_PASSWORD: framework_pass

volumes:
  mysql-data:
